use_frameworks!

platform :ios, '8.0'

target 'TWUserInfoCache_Example' do
  pod 'TWUserInfoCache', :path => '../'
#  pod 'FLEX'

  target 'TWUserInfoCache_Tests' do
    inherit! :search_paths

    
  end
end
